steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', "gcr.io/$PROJECT_ID/setsisaw-api:$_TAG", '.' ]
    env: ["_TAG=$$(echo ${TAG_NAME:-build})"]
images:
  - 'gcr.io/$PROJECT_ID/setsisaw-api'